name: CI

on:
  push:
    branches-ignore: [audit,deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust-version: ['1.56.0', 'stable']

    steps:
    - name: Checkout pkgcraft
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft

    - name: Move pkgcraft into expected location
      run: mv pkgcraft ../

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up rust toolchain ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
        profile: minimal
        override: true
        components: rustfmt

    - name: Set up rust cache
      uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true

    - name: Install cargo-c
      run: cargo install cargo-c

    - name: Build C library
      run: cargo cinstall --prefix=${PWD}/pkgcraft --pkgconfigdir=${PWD}/pkgcraft

    - name: Install meson
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: pip install meson

    - name: Install ninja
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt install -y ninja-build

    - name: Run tests
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        export PKG_CONFIG_PATH=pkgcraft
        meson setup build
        meson test -C build

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout pkgcraft
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft

    - name: Move pkgcraft into expected location
      run: mv pkgcraft ../

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: clippy, rustfmt

    - name: Run rustfmt
      run: cargo fmt --all -- --check

    - name: Set up rust cache
      uses: Swatinem/rust-cache@v1
      with:
        cache-on-failure: true

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
